name: Run Browser Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Start Docker
        run: docker compose up web mocks --detach
        working-directory: test/docker

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Run Cucumber tests
        run: docker compose up cucumber
        working-directory: test/docker

      #      - name: Install Dependencies
      #        run: npm install
      #        working-directory: test/browser

      #      - name: smoke test Toy Front End
      #        env:
      #          BROWSER: chrome-headless
      #        working-directory: test/browser
      #        run: npm run test:browser

      - name: Stop Docker
        run: docker compose down
        working-directory: test/docker
        if: ${{ always() }}

      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}