name: Pre merge deploy to dev
on:
  push:
    branches-ignore:
        - main

jobs:

  run-checks:
    # uses: ./.github/workflows/checks.yml

  check-i18n:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.*
          cache: "npm"

      - name: Install dependencies
        run: yarn install

      - name: Run translation checks
        run: yarn run check-translation

  pre-commit-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"

      - name: Run pre-cpmmit checks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: "--all-files"

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test


  deploy-to-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 10

  development:
    runs-on: ubuntu-latest

    name: deploy to dev
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - name: use upload action
        uses: alphagov/di-devplatform-upload-action-ecr@1.0.3
        with:
          artifact-bucket-name: ${{ secrets.DEV_ARTIFACT_BUCKET }}
          container-sign-kms-key-arn: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
          working-directory: .
          template-file: deploy/template.yaml
          role-to-assume-arn: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
          ecr-repo-name: ${{ secrets.DEV_ECR_REPOSITORY }}
