name: Run Smoke Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Start Docker
        run: docker compose up web mocks --detach
        working-directory: test/docker

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: smoke test Toy Front End
        env:
          BROWSER: chrome-headless
        run: npm run test:browser

      - name: Stop Docker
        run: docker compose down
        working-directory: test/docker
        if: ${{ always() }}
