name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: "--all-files"
