name: Run Browser Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test

      - name: Start Docker
        run: docker compose up --detach
        working-directory: test/browser/docker

      - name: Stop Docker
        run: docker compose down
        working-directory: test/browser/docker
        if: ${{ always() }}
#      - name: smoke test Toy Front End
#        env:
#          BROWSER: chrome-headless
#        run: npm run test:browser:ci
